development:


test:
  secret_key_base: ec89645dab4a375784798c7e8c26716506f8ba75e87b88c03e11e6b41d016619d118b3d2b1f85ec6c29b772033763a170919f0a97958a634e7270d53db90d7bb

production:
  secret_key_base:      <%= ENV["SECRET_KEY_BASE"] %>
  yelp_consumer_key:    <%= ENV["YELP_CONSUMER_KEY"] %>
  yelp_consumer_secret: <%= ENV["YELP_CONSUMER_SECRET"] %>
  yelp_token:           <%= ENV["YELP_TOKEN"] %>
  yelp_token_secret:    <%= ENV["YELP_TOKEN_SECRET"] %>
